In [218]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import warnings
warnings.filterwarnings("ignore")

In [219]:
df_fifa_history = pd.read_csv("C://Code Note//FIFA26//DataCamp Challenge//WorldCupMatches.csv")

In [220]:
df_fifa_history.shape

(4572, 20)

In [221]:
df_fifa_history.head(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA

In [222]:
df_fifa_history[df_fifa_history['Year'] == 2014]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
772,2014.0,12 Jun 2014 - 17:00,Group A,Arena de Sao Paulo,Sao Paulo,Brazil,3.0,1.0,Croatia,,62103.0,1.0,1.0,NISHIMURA Yuichi (JPN),SAGARA Toru (JPN),NAGI Toshiyuki (JPN),255931.0,300186456.0,BRA,CRO
773,2014.0,13 Jun 2014 - 13:00,Group A,Estadio das Dunas,Natal,Mexico,1.0,0.0,Cameroon,,39216.0,0.0,0.0,ROLDAN Wilmar (COL),CLAVIJO Humberto (COL),DIAZ Eduardo (COL),255931.0,300186492.0,MEX,CMR
774,2014.0,13 Jun 2014 - 16:00,Group B,Arena Fonte Nova,Salvador,Spain,1.0,5.0,Netherlands,,48173.0,1.0,1.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255931.0,300186510.0,ESP,NED
775,2014.0,13 Jun 2014 - 18:00,Group B,Arena Pantanal,Cuiaba,Chile,3.0,1.0,Australia,,40275.0,2.0,1.0,Noumandiez DOUE (CIV),YEO Songuifolo (CIV),BIRUMUSHAHU Jean Claude (BDI),255931.0,300186473.0,CHI,AUS
776,2014.0,14 Jun 2014 - 13:00,Group C,Estadio Mineirao,Belo Horizonte,Colombia,3.0,0.0,Greece,,57174.0,1.0,0.0,GEIGER Mark (USA),HURD Sean (USA),FLETCHER Joe (CAN),255931.0,300186471.0,COL,GRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4),63267.0,0.0,0.0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

### Filter out 1986 to 2014

In [223]:
df = df_fifa_history.loc[360:851]

In [224]:
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
360,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,96000.0,0.0,1.0,FREDRIKSSON Erik (SWE),CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308.0,459.0,BUL,ITA
361,1986.0,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0.0,1.0,France,,65500.0,0.0,0.0,SILVA ARCE Hernan (CHI),MENDEZ MOLINA Romulo (GUA),ULLOA MORERA Berny (CRC),308.0,468.0,CAN,FRA
362,1986.0,01 Jun 1986 - 12:00,Group D,Jalisco,Guadalajara,Spain,0.0,1.0,Brazil,,35748.0,0.0,0.0,BAMBRIDGE Christopher (AUS),SOCHA David (USA),KEIZER Jan (NED),308.0,439.0,ESP,BRA
363,1986.0,02 Jun 1986 - 12:00,Group C,Estadio Irapuato,Irapuato,Soviet Union,6.0,0.0,Hungary,,16500.0,3.0,0.0,AGNOLIN Luigi (ITA),COURTNEY George (ENG),BRUMMEIER Horst (AUT),308.0,610.0,URS,HUN
364,1986.0,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3.0,1.0,Korea Republic,,60000.0,2.0,0.0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308.0,395.0,ARG,KOR

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 360 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  492 non-null    float64
 1   Datetime              492 non-null    object
 2   Stage                 492 non-null    object
 3   Stadium               492 non-null    object
 4   City                  492 non-null    object
 5   Home Team Name        492 non-null    object
 6   Home Team Goals       492 non-null    float64
 7   Away Team Goals       492 non-null    float64
 8   Away Team Name        492 non-null    object
 9   Win conditions        492 non-null    object
 10  Attendance            490 non-null    float64
 11  Half-time Home Goals  492 non-null    float64
 12  Half-time Away Goals  492 non-null    float64
 13  Referee               492 non-null    object
 14  Assistant 1           492 non-null    object
 15  Assistant 2           492 non-null    object
 16  RoundID               492 non-null    float64
 17  MatchID               492 non-null    float64
 18  Home Team Initials    492 non-null    object
 19  Away Team Initials    492 non-null    object
dtypes: float64(8), object(12)
memory usage: 77.0+ KB

In [226]:
df.describe()

,Year,Home Team Goals,Away Team Goals,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID
count,492.000000,492.000000,492.000000,490.000000,492.000000,492.000000,4.920000e+02,4.920000e+02
mean,2001.186992,1.365854,1.109756,50705.344898,0.518293,0.436992,1.846275e+07,1.062337e+08
std,9.189873,1.255656,1.154177,18628.512287,0.758973,0.712196,3.386814e+07,1.288355e+08
min,1986.000000,0.000000,0.000000,13800.000000,0.000000,0.000000,3.080000e+02,2.500000e+01
25%,1994.000000,0.000000,0.000000,36285.500000,0.000000,0.000000,3.370000e+02,3.067750e+03
50%,2002.000000,1.000000,1.000000,46862.500000,0.000000,0.000000,2.497220e+05,4.395003e+07
75%,2010.000000,2.000000,2.000000,63108.000000,1.000000,1.000000,4.395010e+07,3.000615e+08
max,2014.000000,8.000000,7.000000,114600.000000,4.000000,5.000000,9.741060e+07,3.001865e+08

In [227]:
df.shape

(492, 20)

In [228]:
df.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              2
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [229]:
df.Stage.unique()

array(['Group A', 'Group C', 'Group D', 'Group F', 'Group B', 'Group E',
       'Round of 16', 'Quarter-finals', 'Semi-finals',
       'Match for third place', 'Final', 'Group H', 'Group G',
       'Third place', 'Play-off for third place'], dtype=object)

#### Feature Engineering

In [230]:
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
360,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,96000.0,0.0,1.0,FREDRIKSSON Erik (SWE),CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308.0,459.0,BUL,ITA
361,1986.0,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0.0,1.0,France,,65500.0,0.0,0.0,SILVA ARCE Hernan (CHI),MENDEZ MOLINA Romulo (GUA),ULLOA MORERA Berny (CRC),308.0,468.0,CAN,FRA
362,1986.0,01 Jun 1986 - 12:00,Group D,Jalisco,Guadalajara,Spain,0.0,1.0,Brazil,,35748.0,0.0,0.0,BAMBRIDGE Christopher (AUS),SOCHA David (USA),KEIZER Jan (NED),308.0,439.0,ESP,BRA
363,1986.0,02 Jun 1986 - 12:00,Group C,Estadio Irapuato,Irapuato,Soviet Union,6.0,0.0,Hungary,,16500.0,3.0,0.0,AGNOLIN Luigi (ITA),COURTNEY George (ENG),BRUMMEIER Horst (AUT),308.0,610.0,URS,HUN
364,1986.0,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3.0,1.0,Korea Republic,,60000.0,2.0,0.0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308.0,395.0,ARG,KOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4),63267.0,0.0,0.0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

In [231]:
df['is_et'] = df['Win conditions'].str.strip().ne('')

In [232]:
def clean_data(txt: str):
    sep = txt.split('(')[1].rstrip(' ) ')
    clean_txt = sep.split(' - ')
    return clean_txt

In [233]:
for i, row in df.iterrows():
    if row['is_et']:
        # print(i)
        # print(row['Win conditions']) debug purpose
        if 'extra time' not in row['Win conditions'] and 'Golden Goal' not in row['Win conditions']:
            goals = clean_data(row['Win conditions'])
            home_goal = goals[0]
            away_goal = goals[1]
            # print(home_goal)
            df.loc[i, "Home Team Goals"] = home_goal
            df.loc[i, "Away Team Goals"] = away_goal
    else:
        # print("Row Skipped")
        pass

In [234]:
df['Winner'] = df.apply(lambda row: row['Home Team Name'] if row['Home Team Goals'] > row['Away Team Goals'] else (row['Away Team Name'] if row['Home Team Goals'] < row['Away Team Goals'] else 'draw'), axis=1)

In [235]:
team_list = {}

In [236]:
df['Home_Team_Elo'] = 0
df['Away_Team_Elo'] = 0

In [237]:
def elo_rating(team):
    if team not in team_list:
        team_list[team] = 1500
        return team_list[team]
    else:
        return team_list[team]

In [238]:
# Functions for elo rating calculation
Home_Adv = 1.10
def calculate_elo_rating(team_a, team_b, stage, winner, Win_Con):

    # print(type(team_a)) For debug

    # Get current ratings
    rating_a = elo_rating(team_a)
    rating_b = elo_rating(team_b)

    # Calculate expected scores
    expected_a = 1 / (1 + 10 ** ((rating_b - rating_a) / 400))
    expected_b = 1 / (1 + 10 ** ((rating_a - rating_b) / 400))

    # Determine actual scores based on winner
    if winner == team_a:
        score_a, score_b = 1, 0
    elif winner == team_b:
        score_a, score_b = 0, 1
    else:  # Draw
        score_a, score_b = 0.5, 0.5

    if stage in ['Group A', 'Group B', 'Group C', 'Group D', 'Group E', 'Group F', 'Group G', 'Group H']:
        k_factor = 20  # Lower K-factor for group stage
        rating_a += k_factor * (score_a - expected_a) * Home_Adv
        rating_b += k_factor * (score_b - expected_b)

        team_list[team_a] = rating_a
        team_list[team_b] = rating_b

        return rating_a, rating_b
    
    elif stage in ['Round of 16', 'Quarter-finals', 'Semi-finals', 'Final', 'Match for third place', 'Play-off for third place', 'Third place']:
        k_factor = 40  # Higher K-factor for knockout stage
        rating_a += k_factor * (score_a - expected_a)
        rating_b += k_factor * (score_b - expected_b)

        team_list[team_a] = rating_a
        team_list[team_b] = rating_b

        return round(rating_a, 2), round(rating_b,2)

In [239]:
for i, row in df.iterrows():
    Home_Team = row['Home Team Name']
    Away_Team = row['Away Team Name']
    Stage = row['Stage']
    Winner = row['Winner']
    Winner_Condition = row['Win conditions']

    if i == 642:
        print(Home_Team, Away_Team, Stage, Winner)
    home_value, away_value = calculate_elo_rating(Home_Team, Away_Team, Stage, Winner, Winner_Condition)

    df.loc[i, "Home_Team_Elo"] = home_value
    df.loc[i, "Away_Team_Elo"] = away_value

    # print(f"Updated row {i}")

Korea Republic Turkey Third place Turkey

In [240]:
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,is_et,Winner,Home_Team_Elo,Away_Team_Elo
360,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,...,CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308.0,459.0,BUL,ITA,False,draw,1500.00,1500.00
361,1986.0,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0.0,1.0,France,,...,MENDEZ MOLINA Romulo (GUA),ULLOA MORERA Berny (CRC),308.0,468.0,CAN,FRA,False,France,1489.00,1510.00
362,1986.0,01 Jun 1986 - 12:00,Group D,Jalisco,Guadalajara,Spain,0.0,1.0,Brazil,,...,SOCHA David (USA),KEIZER Jan (NED),308.0,439.0,ESP,BRA,False,Brazil,1489.00,1510.00
363,1986.0,02 Jun 1986 - 12:00,Group C,Estadio Irapuato,Irapuato,Soviet Union,6.0,0.0,Hungary,,...,COURTNEY George (ENG),BRUMMEIER Horst (AUT),308.0,610.0,URS,HUN,False,Soviet Union,1511.00,1490.00
364,1986.0,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3.0,1.0,Korea Republic,,...,GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308.0,395.0,ARG,KOR,False,Argentina,1511.00,1490.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,4,3,Costa Rica,Netherlands win on penalties (4 - 3),...,RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC,True,Netherlands,1667.95,1502.59
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,...,TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER,False,Germany,1677.98,1764.13
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,2,4,Argentina,Argentina win on penalties (2 - 4),...,DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG,True,Argentina,1649.08,1706.56
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,...,ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED,False,Netherlands,1656.32,1670.74
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,...,Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG,True,Germany,1780.84,1689.84

In [241]:
df_clean = df.drop(columns={"Referee"	,"Assistant 1"	,"Assistant 2"	,"RoundID"	,"MatchID", "Attendance", "Home Team Initials", "Away Team Initials"})

In [245]:
df_clean.head(2)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Half-time Home Goals,Half-time Away Goals,is_et,Winner,Home_Team_Elo,Away_Team_Elo
360,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,0.0,1.0,False,draw,1500.0,1500.0
361,1986.0,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0.0,1.0,France,,0.0,0.0,False,France,1489.0,1510.0

In [246]:
df_clean[df_clean['Winner'] == 'draw'].shape

(91, 16)